{% set name = "bitstruct" %}
{% set version = "8.7.0" %}
{% set sha256 = "d5159eaa0ffaf2b720e7ae8c21d45deb795e82cbf3319f94f826a46f94d52102" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - bitstruct

about:
  home: https://github.com/eerimoq/bitstruct
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python bit pack/unpack package.'
  description: |
    This module is intended to have a similar interface as the python struct module, 
    but working on bits instead of primitive data types (char, int, ...).
  doc_url: http://bitstruct.readthedocs.io/en/latest/
  dev_url: https://github.com/eerimoq/bitstruct

extra:
  recipe-maintainers:
    - eerimoq
    - danielhrisca
