travis:
  secure:
    BINSTAR_TOKEN: KWzQaT2wurIENCkpSunOGoyaQ3SRCMwoFgmSPqvfaaW4/DRzYeAzIFphG0xJ7h/9ptf4d10gxEP4INmWFNRJMFdfOVAooOQtbAGbMcyIpZYsiQjUFLS1c6m+rt5m+wwrzYZvdrvd5LCwN7LCID4Qm1CTdyyBr5tKkr4LQm4LwYedPEw5nKnicqlFA6cfzPDauHOwmzZvwFMKlgiFHpB9WBUHv11fFKMZvuwASvMvh2mXTtdNmNxCGwk1B67r+D5CE4fQgrS6Ws6vRxGDbSVloEfX+V7creACZMzkKY4u9n0Ecu1M0fQYqQJDQwvD58lBEUJqwhKDqRbl4uiHX82+GEKkn/L0cLjrCS4wgsKRpSXiJ2iY4CE8XpzyZOOkz+pelQbXbvHtT3hH7Sq8jY5Vsko9d+2CSCfVK+HoNdBls22UwAw20M1uTe8I297wh9kkpXxQhquotfDgUcN4o73P6NhdRWshtgS44jGYkwLvYQxdxabTS1/+oOoBmJDn10rr5AmROxBvqRH5Y52XuNEKx+Z8cPzOzF956a4gucHw732ZmTLtpnx5fFakJtUbVNdP/JheolJoHEnWpxmyMz4SHneFvEOZ522bH9UGlY2gW9bs+ZUQiz4vGwpjDz2qJSuaUsG4Zf4WD5mAzhdRBcfkq4WjIotUKMXkjqcmz9aB+88=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
