travis:
  secure:
    BINSTAR_TOKEN: T7A0cx/rwfTFA4jt8S3IxEnNao7V17G5TyHkTI5aMgnhYO0Sz1f77We1x0TV0nZjuijDViSv/JoWRUEVC7w5u0y11IdhuEwFNR/SA8ZC2Xx4rH1484b2poBd14Uk+jSonv6EIFYvLGS5WQ1VrRtXB88JfudVNqMkzjp45w+TweYfP9gt1qsCKW+jJvGlK8USxqqzqe69Tw3WVGii/0ZMQMEEvy7g5YqaBTlBkFiev/Nnrf9NLGg4yuVX1geztUji8MSvAb5vfHg4iIPNSvgHZcuBDpMPxZm6BqlBWmH2vCp+/9jpV2z3GmMQeUOxB8ETr8qx9ZQpTMGn+W7v62TXjkwhdgScyshIJJgvrw9c9DzQrh1zkIiQCoF4x480f5rwEc3LEz5+XeriAXtK7mDGwDuKxlrdc/USU0M370reOko+O1AGPGStUZrGCcGb/mox14hf8CshW9jBGLENquqoPqRIANXKnO1B+lMR59RqUF+VR0sVgnbfjeYkMOtLjxhMq7CvnoHLJHVJeWHhYcKVJMUWs8/Hi5Q1bblysuooCIclIKa+1suV8AkwKIsOC6ZNbC2yAf3qTjD8tH+EihKjD0kdSZ7IBPatovr3LErsddFylcL/iBAv81g2BfHxLOkplDqCvpSFOyLTJPWtTSDY8PX934L3+TlNtliqzI2NEuQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
